#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CampingBase

#include "Basic.hpp"

#include "BP_CampingBase_classes.hpp"
#include "BP_CampingBase_parameters.hpp"


namespace SDK
{

// Function BP_CampingBase.BP_CampingBase_C.BuildCampTrailer
// (BlueprintCallable, BlueprintEvent)

void ABP_CampingBase_C::BuildCampTrailer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "BuildCampTrailer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.BuildingStateUpd
// (BlueprintCallable, BlueprintEvent)

void ABP_CampingBase_C::BuildingStateUpd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "BuildingStateUpd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.CampingBuildingState
// (BlueprintCallable, BlueprintEvent)

void ABP_CampingBase_C::CampingBuildingState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "CampingBuildingState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.CampingBuilt
// (BlueprintCallable, BlueprintEvent)

void ABP_CampingBase_C::CampingBuilt()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "CampingBuilt");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.CampingBuiltV2
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_CampingBase_C::CampingBuiltV2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "CampingBuiltV2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.ChangeToDefaultMaterials
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_CampingBase_C::ChangeToDefaultMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "ChangeToDefaultMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.ChangeToStateMaterials
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_CampingBase_C::ChangeToStateMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "ChangeToStateMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.CheckForSurface
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    CanBePlaced                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CampingBase_C::CheckForSurface(bool* CanBePlaced)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "CheckForSurface");

	Params::BP_CampingBase_C_CheckForSurface Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CanBePlaced != nullptr)
		*CanBePlaced = Parms.CanBePlaced;
}


// Function BP_CampingBase.BP_CampingBase_C.ExecuteUbergraph_BP_CampingBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CampingBase_C::ExecuteUbergraph_BP_CampingBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "ExecuteUbergraph_BP_CampingBase");

	Params::BP_CampingBase_C_ExecuteUbergraph_BP_CampingBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CampingBase.BP_CampingBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CampingBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.RemoveSelf
// (BlueprintCallable, BlueprintEvent)

void ABP_CampingBase_C::RemoveSelf()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "RemoveSelf");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.SetCampBuildingState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    CanBuildCamping                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CampingBase_C::SetCampBuildingState(bool CanBuildCamping)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "SetCampBuildingState");

	Params::BP_CampingBase_C_SetCampBuildingState Parms{};

	Parms.CanBuildCamping = CanBuildCamping;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CampingBase.BP_CampingBase_C.SetCollisionResponse
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    CollisionEnabled                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CampingBase_C::SetCollisionResponse(bool CollisionEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "SetCollisionResponse");

	Params::BP_CampingBase_C_SetCollisionResponse Parms{};

	Parms.CollisionEnabled = CollisionEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CampingBase.BP_CampingBase_C.StoreAllMaterials
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_CampingBase_C::StoreAllMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "StoreAllMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.StoreAllMeshes
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_CampingBase_C::StoreAllMeshes()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "StoreAllMeshes");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CampingBase.BP_CampingBase_C.UpdateLocationAndRotation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRotator                         Rotation                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_CampingBase_C::UpdateLocationAndRotation(const struct FVector& Location, const struct FRotator& Rotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CampingBase_C", "UpdateLocationAndRotation");

	Params::BP_CampingBase_C_UpdateLocationAndRotation Parms{};

	Parms.Location = std::move(Location);
	Parms.Rotation = std::move(Rotation);

	UObject::ProcessEvent(Func, &Parms);
}

}

