#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DarkCube

#include "Basic.hpp"

#include "BP_DarkCube_classes.hpp"
#include "BP_DarkCube_parameters.hpp"


namespace SDK
{

// Function BP_DarkCube.BP_DarkCube_C.ExecuteUbergraph_BP_DarkCube
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DarkCube_C::ExecuteUbergraph_BP_DarkCube(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DarkCube_C", "ExecuteUbergraph_BP_DarkCube");

	Params::BP_DarkCube_C_ExecuteUbergraph_BP_DarkCube Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DarkCube.BP_DarkCube_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_DarkCube_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DarkCube_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DarkCube.BP_DarkCube_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DarkCube_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DarkCube_C", "ReceiveTick");

	Params::BP_DarkCube_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

