#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_TabType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_TabType.E_TabType
// NumValues: 0x000A
enum class E_TabType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator8                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator4                           = 5,
	NewEnumerator5                           = 6,
	NewEnumerator7                           = 7,
	NewEnumerator9                           = 8,
	E_MAX                                    = 9,
};

}

