#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IsWelcome

#include "Basic.hpp"

#include "AGSGraphRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass isWelcome.isWelcome_C
// 0x0008 (0x0040 - 0x0038)
class UIsWelcome_C final : public UAGSCondition
{
public:
	bool                                          IsWelcome;                                         // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool VerifyCondition(class APlayerController* PlayerController) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"isWelcome_C">();
	}
	static class UIsWelcome_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UIsWelcome_C>();
	}
};
static_assert(alignof(UIsWelcome_C) == 0x000008, "Wrong alignment on UIsWelcome_C");
static_assert(sizeof(UIsWelcome_C) == 0x000040, "Wrong size on UIsWelcome_C");
static_assert(offsetof(UIsWelcome_C, IsWelcome) == 0x000038, "Member 'UIsWelcome_C::IsWelcome' has a wrong offset!");

}

