#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LensFlare_BP

#include "Basic.hpp"

#include "LensFlare_BP_classes.hpp"
#include "LensFlare_BP_parameters.hpp"


namespace SDK
{

// Function LensFlare_BP.LensFlare_BP_C.ExecuteUbergraph_LensFlare_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALensFlare_BP_C::ExecuteUbergraph_LensFlare_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LensFlare_BP_C", "ExecuteUbergraph_LensFlare_BP");

	Params::LensFlare_BP_C_ExecuteUbergraph_LensFlare_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LensFlare_BP.LensFlare_BP_C.InitFlare
// (Public, BlueprintCallable, BlueprintEvent)

void ALensFlare_BP_C::InitFlare()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LensFlare_BP_C", "InitFlare");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LensFlare_BP.LensFlare_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALensFlare_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LensFlare_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LensFlare_BP.LensFlare_BP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALensFlare_BP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LensFlare_BP_C", "ReceiveTick");

	Params::LensFlare_BP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LensFlare_BP.LensFlare_BP_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ALensFlare_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LensFlare_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

