#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LevelStreamerFunctions

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LevelStreamerFunctions.LevelStreamerFunctions_C
// 0x0000 (0x0028 - 0x0028)
class ULevelStreamerFunctions_C final : public UBlueprintFunctionLibrary
{
public:
	static void GetStreamer(class UObject* __WorldContext, class ALevelStreamer_C** Streamer);
	static void GetStreamLevelByClass(const class UObject* Object, class UObject* __WorldContext, class FName* ReturnValue1);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LevelStreamerFunctions_C">();
	}
	static class ULevelStreamerFunctions_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULevelStreamerFunctions_C>();
	}
};
static_assert(alignof(ULevelStreamerFunctions_C) == 0x000008, "Wrong alignment on ULevelStreamerFunctions_C");
static_assert(sizeof(ULevelStreamerFunctions_C) == 0x000028, "Wrong size on ULevelStreamerFunctions_C");

}

