#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LG2_LootRareType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum LG2_LootRareType.LG2_LootRareType
// NumValues: 0x0004
enum class ELG2_LootRareType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	LG2_MAX                                  = 3,
};

}

