#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_CoinIntro

#include "Basic.hpp"

#include "LS_CoinIntro_classes.hpp"
#include "LS_CoinIntro_parameters.hpp"


namespace SDK
{

// Function LS_CoinIntro.LS_CoinIntro_DirectorBP_C.ExecuteUbergraph_LS_CoinIntro (Director BP)
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULS_CoinIntro_DirectorBP_C::ExecuteUbergraph_LS_CoinIntro__Director_BP_(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_CoinIntro_DirectorBP_C", "ExecuteUbergraph_LS_CoinIntro (Director BP)");

	Params::LS_CoinIntro_DirectorBP_C_ExecuteUbergraph_LS_CoinIntro__Director_BP_ Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LS_CoinIntro.LS_CoinIntro_DirectorBP_C.FntasticLogo_Hide
// (BlueprintCallable, BlueprintEvent)

void ULS_CoinIntro_DirectorBP_C::FntasticLogo_Hide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_CoinIntro_DirectorBP_C", "FntasticLogo_Hide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_CoinIntro.LS_CoinIntro_DirectorBP_C.FntasticLogo_Show
// (BlueprintCallable, BlueprintEvent)

void ULS_CoinIntro_DirectorBP_C::FntasticLogo_Show()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_CoinIntro_DirectorBP_C", "FntasticLogo_Show");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_CoinIntro.LS_CoinIntro_DirectorBP_C.MytonaLogo_Hide
// (BlueprintCallable, BlueprintEvent)

void ULS_CoinIntro_DirectorBP_C::MytonaLogo_Hide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_CoinIntro_DirectorBP_C", "MytonaLogo_Hide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_CoinIntro.LS_CoinIntro_DirectorBP_C.MytonaLogo_Show
// (BlueprintCallable, BlueprintEvent)

void ULS_CoinIntro_DirectorBP_C::MytonaLogo_Show()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_CoinIntro_DirectorBP_C", "MytonaLogo_Show");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_CoinIntro.LS_CoinIntro_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_CoinIntro (Director BP)
// (Public, BlueprintCallable, BlueprintEvent)

void ULS_CoinIntro_DirectorBP_C::SequenceEvent__ENTRYPOINTLS_CoinIntro__Director_BP_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_CoinIntro_DirectorBP_C", "SequenceEvent__ENTRYPOINTLS_CoinIntro (Director BP)");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_CoinIntro.LS_CoinIntro_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_CoinIntro (Director BP)_0
// (Public, BlueprintCallable, BlueprintEvent)

void ULS_CoinIntro_DirectorBP_C::SequenceEvent__ENTRYPOINTLS_CoinIntro__Director_BP__0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_CoinIntro_DirectorBP_C", "SequenceEvent__ENTRYPOINTLS_CoinIntro (Director BP)_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_CoinIntro.LS_CoinIntro_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_CoinIntro (Director BP)_1
// (Public, BlueprintCallable, BlueprintEvent)

void ULS_CoinIntro_DirectorBP_C::SequenceEvent__ENTRYPOINTLS_CoinIntro__Director_BP__1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_CoinIntro_DirectorBP_C", "SequenceEvent__ENTRYPOINTLS_CoinIntro (Director BP)_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_CoinIntro.LS_CoinIntro_DirectorBP_C.SequenceEvent__ENTRYPOINTLS_CoinIntro (Director BP)_2
// (Public, BlueprintCallable, BlueprintEvent)

void ULS_CoinIntro_DirectorBP_C::SequenceEvent__ENTRYPOINTLS_CoinIntro__Director_BP__2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_CoinIntro_DirectorBP_C", "SequenceEvent__ENTRYPOINTLS_CoinIntro (Director BP)_2");

	UObject::ProcessEvent(Func, nullptr);
}

}

