#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SG_DeathCount

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SG_DeathCount.SG_DeathCount_C
// 0x0008 (0x0030 - 0x0028)
class USG_DeathCount_C final : public USaveGame
{
public:
	int32                                         DeathCount;                                        // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SG_DeathCount_C">();
	}
	static class USG_DeathCount_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USG_DeathCount_C>();
	}
};
static_assert(alignof(USG_DeathCount_C) == 0x000008, "Wrong alignment on USG_DeathCount_C");
static_assert(sizeof(USG_DeathCount_C) == 0x000030, "Wrong size on USG_DeathCount_C");
static_assert(offsetof(USG_DeathCount_C, DeathCount) == 0x000028, "Member 'USG_DeathCount_C::DeathCount' has a wrong offset!");

}

