#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SurvInterface

#include "Basic.hpp"

#include "SurvInterface_classes.hpp"
#include "SurvInterface_parameters.hpp"


namespace SDK
{

// Function SurvInterface.SurvInterface_C.AddCharacterRotation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FRotator                         Amount                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ISurvInterface_C::AddCharacterRotation(const struct FRotator& Amount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "AddCharacterRotation");

	Params::SurvInterface_C_AddCharacterRotation Parms{};

	Parms.Amount = std::move(Amount);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurvInterface.SurvInterface_C.AnimNotifyTurningInPlace
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage*                     TurnIPMontage                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ShouldTurn                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    TurningIP                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    TurningRight                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::AnimNotifyTurningInPlace(class UAnimMontage* TurnIPMontage, bool ShouldTurn, bool TurningIP, bool TurningRight)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "AnimNotifyTurningInPlace");

	Params::SurvInterface_C_AnimNotifyTurningInPlace Parms{};

	Parms.TurnIPMontage = TurnIPMontage;
	Parms.ShouldTurn = ShouldTurn;
	Parms.TurningIP = TurningIP;
	Parms.TurningRight = TurningRight;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurvInterface.SurvInterface_C.BPI_CameraShake
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ShakeClass                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    NeedChangeScale                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Scale                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::BPI_CameraShake(class UClass* ShakeClass, bool NeedChangeScale, double Scale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "BPI_CameraShake");

	Params::SurvInterface_C_BPI_CameraShake Parms{};

	Parms.ShakeClass = ShakeClass;
	Parms.NeedChangeScale = NeedChangeScale;
	Parms.Scale = Scale;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurvInterface.SurvInterface_C.CallEatMesh
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ItemType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  DurationAttached                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  AnimDelay                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  DissappearDelay                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  PlayRate                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::CallEatMesh(class FName ItemType, double DurationAttached, double AnimDelay, double DissappearDelay, double PlayRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "CallEatMesh");

	Params::SurvInterface_C_CallEatMesh Parms{};

	Parms.ItemType = ItemType;
	Parms.DurationAttached = DurationAttached;
	Parms.AnimDelay = AnimDelay;
	Parms.DissappearDelay = DissappearDelay;
	Parms.PlayRate = PlayRate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurvInterface.SurvInterface_C.CheckEndEat
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Eat_                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::CheckEndEat(bool* Eat_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "CheckEndEat");

	Params::SurvInterface_C_CheckEndEat Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Eat_ != nullptr)
		*Eat_ = Parms.Eat_;
}


// Function SurvInterface.SurvInterface_C.GetCameraOffset
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          PelvisOffset                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          InterpOffset                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::GetCameraOffset(struct FVector* PelvisOffset, struct FVector* InterpOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "GetCameraOffset");

	Params::SurvInterface_C_GetCameraOffset Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PelvisOffset != nullptr)
		*PelvisOffset = std::move(Parms.PelvisOffset);

	if (InterpOffset != nullptr)
		*InterpOffset = std::move(Parms.InterpOffset);
}


// Function SurvInterface.SurvInterface_C.GetSurvController
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASurvPC_C*                        SurvPC                                                 (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::GetSurvController(class ASurvPC_C** SurvPC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "GetSurvController");

	Params::SurvInterface_C_GetSurvController Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SurvPC != nullptr)
		*SurvPC = Parms.SurvPC;
}


// Function SurvInterface.SurvInterface_C.MovementModeChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EMovementMode                           NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::MovementModeChanged(EMovementMode NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "MovementModeChanged");

	Params::SurvInterface_C_MovementModeChanged Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurvInterface.SurvInterface_C.NotifyItemUsing
// (Public, BlueprintCallable, BlueprintEvent)

void ISurvInterface_C::NotifyItemUsing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "NotifyItemUsing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurvInterface.SurvInterface_C.PlayMontage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage*                     AnimMontage                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    IsHipfire                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Reloading                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  PlayRate                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  StartTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::PlayMontage(class UAnimMontage* AnimMontage, bool IsHipfire, bool Reloading, double PlayRate, double StartTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "PlayMontage");

	Params::SurvInterface_C_PlayMontage Parms{};

	Parms.AnimMontage = AnimMontage;
	Parms.IsHipfire = IsHipfire;
	Parms.Reloading = Reloading;
	Parms.PlayRate = PlayRate;
	Parms.StartTime = StartTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurvInterface.SurvInterface_C.ResetItemUsingAnim
// (Public, BlueprintCallable, BlueprintEvent)

void ISurvInterface_C::ResetItemUsingAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "ResetItemUsingAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SurvInterface.SurvInterface_C.SetItemUsingAnim
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimSequence*                    Anim                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    SpecialItem                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CanMove                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    HasStandAnim                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    WepNotHiding                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::SetItemUsingAnim(class UAnimSequence* Anim, bool SpecialItem, bool CanMove, bool HasStandAnim, bool WepNotHiding)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "SetItemUsingAnim");

	Params::SurvInterface_C_SetItemUsingAnim Parms{};

	Parms.Anim = Anim;
	Parms.SpecialItem = SpecialItem;
	Parms.CanMove = CanMove;
	Parms.HasStandAnim = HasStandAnim;
	Parms.WepNotHiding = WepNotHiding;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurvInterface.SurvInterface_C.SetReloadState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::SetReloadState(bool State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "SetReloadState");

	Params::SurvInterface_C_SetReloadState Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SurvInterface.SurvInterface_C.SetWeaponType
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EBPE_Weapon_Type                        WeaponType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ISurvInterface_C::SetWeaponType(EBPE_Weapon_Type WeaponType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SurvInterface_C", "SetWeaponType");

	Params::SurvInterface_C_SetWeaponType Parms{};

	Parms.WeaponType = WeaponType;

	UObject::ProcessEvent(Func, &Parms);
}

}

