#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_PlayerMain

#include "Basic.hpp"

#include "UIW_PlayerMain_classes.hpp"
#include "UIW_PlayerMain_parameters.hpp"


namespace SDK
{

// Function UIW_PlayerMain.UIW_PlayerMain_C.AddInvideToHomeOffer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InviteIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           PlayerNameOfferer                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class APS_TDB_C*                        NewVar                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UWBP_inviteHomeOffer_C*           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWBP_inviteHomeOffer_C* UUIW_PlayerMain_C::AddInvideToHomeOffer(int32 InviteIndex, const class FString& PlayerNameOfferer, class APS_TDB_C* NewVar)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "AddInvideToHomeOffer");

	Params::UIW_PlayerMain_C_AddInvideToHomeOffer Parms{};

	Parms.InviteIndex = InviteIndex;
	Parms.PlayerNameOfferer = std::move(PlayerNameOfferer);
	Parms.NewVar = NewVar;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.AddInvite
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InvitedSquadIndex                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           PlayerNameInviter                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UWBP_Offer_C*                     InviteWidget                                           (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::AddInvite(int32 InvitedSquadIndex, const class FString& PlayerNameInviter, class UWBP_Offer_C** InviteWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "AddInvite");

	Params::UIW_PlayerMain_C_AddInvite Parms{};

	Parms.InvitedSquadIndex = InvitedSquadIndex;
	Parms.PlayerNameInviter = std::move(PlayerNameInviter);

	UObject::ProcessEvent(Func, &Parms);

	if (InviteWidget != nullptr)
		*InviteWidget = Parms.InviteWidget;
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.AddInviteWidget
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InvitedSquadIndex                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           PlayerNameInviter                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::AddInviteWidget(int32 InvitedSquadIndex, const class FString& PlayerNameInviter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "AddInviteWidget");

	Params::UIW_PlayerMain_C_AddInviteWidget Parms{};

	Parms.InvitedSquadIndex = InvitedSquadIndex;
	Parms.PlayerNameInviter = std::move(PlayerNameInviter);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.AddTradeOffer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           PlayerNameOfferer                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class ASurvivalPlayer_C*                TradeOfferer                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UWBP_Offer_C*                     TradeOfferWidget                                       (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::AddTradeOffer(const class FString& PlayerNameOfferer, class ASurvivalPlayer_C* TradeOfferer, class UWBP_Offer_C** TradeOfferWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "AddTradeOffer");

	Params::UIW_PlayerMain_C_AddTradeOffer Parms{};

	Parms.PlayerNameOfferer = std::move(PlayerNameOfferer);
	Parms.TradeOfferer = TradeOfferer;

	UObject::ProcessEvent(Func, &Parms);

	if (TradeOfferWidget != nullptr)
		*TradeOfferWidget = Parms.TradeOfferWidget;
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.AddWorkRPMessage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  TotalTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             WorkRPName                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             WorkRPDescription                                      (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             WorkRP_Count_current                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             WorkRP_Count_total                                     (BlueprintVisible, BlueprintReadOnly, Parm)
// class UW_WorkRPNotification_C*          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UW_WorkRPNotification_C* UUIW_PlayerMain_C::AddWorkRPMessage(double TotalTime, const class FText& WorkRPName, const class FText& WorkRPDescription, const class FText& WorkRP_Count_current, const class FText& WorkRP_Count_total)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "AddWorkRPMessage");

	Params::UIW_PlayerMain_C_AddWorkRPMessage Parms{};

	Parms.TotalTime = TotalTime;
	Parms.WorkRPName = std::move(WorkRPName);
	Parms.WorkRPDescription = std::move(WorkRPDescription);
	Parms.WorkRP_Count_current = std::move(WorkRP_Count_current);
	Parms.WorkRP_Count_total = std::move(WorkRP_Count_total);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.AssignNewPlayer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASurvivalPlayer_C*                Param_Player                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::AssignNewPlayer(class ASurvivalPlayer_C* Param_Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "AssignNewPlayer");

	Params::UIW_PlayerMain_C_AssignNewPlayer Parms{};

	Parms.Param_Player = Param_Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.BleedRemovedEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::BleedRemovedEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "BleedRemovedEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_PlayerMain_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.DisableCarStats
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::DisableCarStats()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "DisableCarStats");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.DurabilityIncreaseCancel
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::DurabilityIncreaseCancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "DurabilityIncreaseCancel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.DurabilityIncreaseCancelEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::DurabilityIncreaseCancelEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "DurabilityIncreaseCancelEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.DurabilityIncreaseFinish
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::DurabilityIncreaseFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "DurabilityIncreaseFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.DurabilityIncreaseFinishEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::DurabilityIncreaseFinishEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "DurabilityIncreaseFinishEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.DurabilityIncreaseStart
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::DurabilityIncreaseStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "DurabilityIncreaseStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.DurabilityIncreaseStartEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::DurabilityIncreaseStartEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "DurabilityIncreaseStartEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.EnableCarStats
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Vehicle                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::EnableCarStats(class AActor* Vehicle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "EnableCarStats");

	Params::UIW_PlayerMain_C_EnableCarStats Parms{};

	Parms.Vehicle = Vehicle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ExecuteUbergraph_UIW_PlayerMain
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ExecuteUbergraph_UIW_PlayerMain(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ExecuteUbergraph_UIW_PlayerMain");

	Params::UIW_PlayerMain_C_ExecuteUbergraph_UIW_PlayerMain Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.FillProgressBar
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::FillProgressBar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "FillProgressBar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.FireModeChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EBPE_FireMode                           FireMode                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::FireModeChanged(EBPE_FireMode FireMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "FireModeChanged");

	Params::UIW_PlayerMain_C_FireModeChanged Parms{};

	Parms.FireMode = FireMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.FuelIncreaseCancel
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::FuelIncreaseCancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "FuelIncreaseCancel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.FuelIncreaseCancelEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::FuelIncreaseCancelEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "FuelIncreaseCancelEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.FuelIncreaseFinish
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::FuelIncreaseFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "FuelIncreaseFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.FuelIncreaseFinishEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::FuelIncreaseFinishEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "FuelIncreaseFinishEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.FuelIncreaseStart
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::FuelIncreaseStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "FuelIncreaseStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.FuelIncreaseStartEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::FuelIncreaseStartEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "FuelIncreaseStartEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.GetBleedEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::GetBleedEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "GetBleedEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.GetDamageEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::GetDamageEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "GetDamageEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.GetLeaveCheckDisplayed
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    LeaveQueueDisplayed                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::GetLeaveCheckDisplayed(bool* LeaveQueueDisplayed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "GetLeaveCheckDisplayed");

	Params::UIW_PlayerMain_C_GetLeaveCheckDisplayed Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (LeaveQueueDisplayed != nullptr)
		*LeaveQueueDisplayed = Parms.LeaveQueueDisplayed;
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.GrenadeStat
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Toggle                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FFGrenadeInfo                    Grenade_Info                                           (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UUIW_PlayerMain_C::GrenadeStat(bool Toggle, const struct FFGrenadeInfo& Grenade_Info)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "GrenadeStat");

	Params::UIW_PlayerMain_C_GrenadeStat Parms{};

	Parms.Toggle = Toggle;
	Parms.Grenade_Info = std::move(Grenade_Info);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.HealthChangeEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  CriticalValue                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::HealthChangeEvent(double CriticalValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "HealthChangeEvent");

	Params::UIW_PlayerMain_C_HealthChangeEvent Parms{};

	Parms.CriticalValue = CriticalValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.HideBlackScreen
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::HideBlackScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "HideBlackScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.HideDropCanisterMessage
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::HideDropCanisterMessage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "HideDropCanisterMessage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.HideUI
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   PlaybackSpeed                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::HideUI(float PlaybackSpeed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "HideUI");

	Params::UIW_PlayerMain_C_HideUI Parms{};

	Parms.PlaybackSpeed = PlaybackSpeed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.HideWarningMessage
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::HideWarningMessage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "HideWarningMessage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.Init Progress Bar
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::Init_Progress_Bar(float Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "Init Progress Bar");

	Params::UIW_PlayerMain_C_Init_Progress_Bar Parms{};

	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.InstantHideNotify
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::InstantHideNotify()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "InstantHideNotify");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.LateInteractCancel
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::LateInteractCancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "LateInteractCancel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.LateInteractCancelEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::LateInteractCancelEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "LateInteractCancelEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.LateInteractFinish
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::LateInteractFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "LateInteractFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.LateInteractFinishEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::LateInteractFinishEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "LateInteractFinishEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.LateInteractStart
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::LateInteractStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "LateInteractStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.LateInteractStartEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::LateInteractStartEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "LateInteractStartEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_PlayerMain_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.RadialInteractionHide
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::RadialInteractionHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "RadialInteractionHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.SetBleeding
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewBleeding                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::SetBleeding(bool NewBleeding)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "SetBleeding");

	Params::UIW_PlayerMain_C_SetBleeding Parms{};

	Parms.NewBleeding = NewBleeding;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.SetHitAnimation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsKillingHit                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::SetHitAnimation(bool IsKillingHit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "SetHitAnimation");

	Params::UIW_PlayerMain_C_SetHitAnimation Parms{};

	Parms.IsKillingHit = IsKillingHit;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.SetHouseActivatorHint
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewActive                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::SetHouseActivatorHint(bool NewActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "SetHouseActivatorHint");

	Params::UIW_PlayerMain_C_SetHouseActivatorHint Parms{};

	Parms.NewActive = NewActive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.SetSpeaking
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APS_TDB_C*                        PS                                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// bool                                    Speaking                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::SetSpeaking(const class APS_TDB_C*& PS, bool Speaking)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "SetSpeaking");

	Params::UIW_PlayerMain_C_SetSpeaking Parms{};

	Parms.PS = PS;
	Parms.Speaking = Speaking;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShaderEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::ShaderEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShaderEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.Show Leave Check
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Show                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::Show_Leave_Check(bool Show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "Show Leave Check");

	Params::UIW_PlayerMain_C_Show_Leave_Check Parms{};

	Parms.Show = Show;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowBigText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowBigText(const class FString& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowBigText");

	Params::UIW_PlayerMain_C_ShowBigText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowBlackScreen
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::ShowBlackScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowBlackScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowDropCanisterMessage
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::ShowDropCanisterMessage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowDropCanisterMessage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowDurabilityMessage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Vehicle                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowDurabilityMessage(class AActor* Vehicle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowDurabilityMessage");

	Params::UIW_PlayerMain_C_ShowDurabilityMessage Parms{};

	Parms.Vehicle = Vehicle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowExecuteMesssage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASurvivalPlayer_C*                Param_Player                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    IsSelfTarget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowExecuteMesssage(class ASurvivalPlayer_C* Param_Player, bool IsSelfTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowExecuteMesssage");

	Params::UIW_PlayerMain_C_ShowExecuteMesssage Parms{};

	Parms.Param_Player = Param_Player;
	Parms.IsSelfTarget = IsSelfTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowFuelMessage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             CanisterVolume                                         (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             CarFuel                                                (BlueprintVisible, BlueprintReadOnly, Parm)
// class AActor*                           Param_FocusedVehicle                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowFuelMessage(const class FText& CanisterVolume, const class FText& CarFuel, class AActor* Param_FocusedVehicle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowFuelMessage");

	Params::UIW_PlayerMain_C_ShowFuelMessage Parms{};

	Parms.CanisterVolume = std::move(CanisterVolume);
	Parms.CarFuel = std::move(CarFuel);
	Parms.Param_FocusedVehicle = Param_FocusedVehicle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowInteractMessage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHold                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  HoldTime                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             ActionText                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    ShowAtScreen                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USceneComponent*                  AtPosition                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UW_Interact_C*                    CustomInteractWidget                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   Inactive                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowInteractMessage(bool IsHold, double HoldTime, const class FText& ActionText, bool ShowAtScreen, class USceneComponent* AtPosition, bool Visible, class UW_Interact_C* CustomInteractWidget, int32 Inactive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowInteractMessage");

	Params::UIW_PlayerMain_C_ShowInteractMessage Parms{};

	Parms.IsHold = IsHold;
	Parms.HoldTime = HoldTime;
	Parms.ActionText = std::move(ActionText);
	Parms.ShowAtScreen = ShowAtScreen;
	Parms.AtPosition = AtPosition;
	Parms.Visible = Visible;
	Parms.CustomInteractWidget = CustomInteractWidget;
	Parms.Inactive = Inactive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowInteractTrailer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHold                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  HoldTime                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             ActionText                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UUIW_PlayerMain_C::ShowInteractTrailer(bool IsHold, double HoldTime, const class FText& ActionText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowInteractTrailer");

	Params::UIW_PlayerMain_C_ShowInteractTrailer Parms{};

	Parms.IsHold = IsHold;
	Parms.HoldTime = HoldTime;
	Parms.ActionText = std::move(ActionText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowPingIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::ShowPingIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowPingIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowPoint
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  CurrentDistance                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  TargetDistance                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USceneComponent*                  Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowPoint(double CurrentDistance, double TargetDistance, class USceneComponent* Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowPoint");

	Params::UIW_PlayerMain_C_ShowPoint Parms{};

	Parms.CurrentDistance = CurrentDistance;
	Parms.TargetDistance = TargetDistance;
	Parms.Target = Target;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowQuestMessage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NPC                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Message                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Param_PlaySound                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowQuestMessage(class FName NPC, class FName Message, bool Param_PlaySound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowQuestMessage");

	Params::UIW_PlayerMain_C_ShowQuestMessage Parms{};

	Parms.NPC = NPC;
	Parms.Message = Message;
	Parms.Param_PlaySound = Param_PlaySound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowSimpleText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowSimpleText(const class FString& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowSimpleText");

	Params::UIW_PlayerMain_C_ShowSimpleText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowTextWindow
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowTextWindow(const class FString& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowTextWindow");

	Params::UIW_PlayerMain_C_ShowTextWindow Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowTrailerCarRepair
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::ShowTrailerCarRepair()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowTrailerCarRepair");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowUI
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   PlaybackSpeed                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowUI(float PlaybackSpeed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowUI");

	Params::UIW_PlayerMain_C_ShowUI Parms{};

	Parms.PlaybackSpeed = PlaybackSpeed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowWarningMessage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             MessageText                                            (BlueprintVisible, BlueprintReadOnly, Parm)
// class UFMODEvent*                       FMODEvent                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    IsWarningMessage                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowWarningMessage(const class FText& MessageText, class UFMODEvent* FMODEvent, bool IsWarningMessage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowWarningMessage");

	Params::UIW_PlayerMain_C_ShowWarningMessage Parms{};

	Parms.MessageText = std::move(MessageText);
	Parms.FMODEvent = FMODEvent;
	Parms.IsWarningMessage = IsWarningMessage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ShowWeaponWidget
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Show                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ShowWeaponWidget(bool Show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ShowWeaponWidget");

	Params::UIW_PlayerMain_C_ShowWeaponWidget Parms{};

	Parms.Show = Show;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "Tick");

	Params::UIW_PlayerMain_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.ToggleGrenade
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FFGrenadeInfo                    GrenadeInfo                                            (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// bool                                    ToggleWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::ToggleGrenade(const struct FFGrenadeInfo& GrenadeInfo, bool ToggleWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "ToggleGrenade");

	Params::UIW_PlayerMain_C_ToggleGrenade Parms{};

	Parms.GrenadeInfo = std::move(GrenadeInfo);
	Parms.ToggleWidget = ToggleWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.UpdateDurabilityProgressBar
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::UpdateDurabilityProgressBar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "UpdateDurabilityProgressBar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.UpdateFireModeWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EBPE_FireMode                           Mode                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_PlayerMain_C::UpdateFireModeWidget(EBPE_FireMode Mode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "UpdateFireModeWidget");

	Params::UIW_PlayerMain_C_UpdateFireModeWidget Parms{};

	Parms.Mode = Mode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.UpdateFuelProgressBar
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::UpdateFuelProgressBar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "UpdateFuelProgressBar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.UpdateInteractPosition
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::UpdateInteractPosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "UpdateInteractPosition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.UpdateInteractProgressBar
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::UpdateInteractProgressBar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "UpdateInteractProgressBar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.UpdateKDCounter
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::UpdateKDCounter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "UpdateKDCounter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.UpdateKDCounterEvent
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::UpdateKDCounterEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "UpdateKDCounterEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_PlayerMain.UIW_PlayerMain_C.UpdateSquadList
// (BlueprintCallable, BlueprintEvent)

void UUIW_PlayerMain_C::UpdateSquadList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_PlayerMain_C", "UpdateSquadList");

	UObject::ProcessEvent(Func, nullptr);
}

}

