#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_FakeItemSlot

#include "Basic.hpp"

#include "W_FakeItemSlot_classes.hpp"
#include "W_FakeItemSlot_parameters.hpp"


namespace SDK
{

// Function W_FakeItemSlot.W_FakeItemSlot_C.ExecuteUbergraph_W_FakeItemSlot
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FakeItemSlot_C::ExecuteUbergraph_W_FakeItemSlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FakeItemSlot_C", "ExecuteUbergraph_W_FakeItemSlot");

	Params::W_FakeItemSlot_C_ExecuteUbergraph_W_FakeItemSlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FakeItemSlot.W_FakeItemSlot_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FakeItemSlot_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FakeItemSlot_C", "PreConstruct");

	Params::W_FakeItemSlot_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FakeItemSlot.W_FakeItemSlot_C.SetImage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPaperSprite*                     Image                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_FakeItemSlot_C::SetImage(class UPaperSprite* Image)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FakeItemSlot_C", "SetImage");

	Params::W_FakeItemSlot_C_SetImage Parms{};

	Parms.Image = Image;

	UObject::ProcessEvent(Func, &Parms);
}

}

