#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ItemInteractionValueChangeButton

#include "Basic.hpp"

#include "WBP_ItemInteractionValueChangeButton_classes.hpp"
#include "WBP_ItemInteractionValueChangeButton_parameters.hpp"


namespace SDK
{

// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_ItemInteractionValueChangeButton_C::BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_ItemInteractionValueChangeButton_C::BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_ItemInteractionValueChangeButton_C::BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_ItemInteractionValueChangeButton_C::BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "BndEvt__WBP_ItemInteractionValueChangeButton_Button_ChangeCount_K2Node_ComponentBoundEvent_4_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.ButtonActionHover
// (BlueprintCallable, BlueprintEvent)

void UWBP_ItemInteractionValueChangeButton_C::ButtonActionHover()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "ButtonActionHover");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.ButtonActionUnhover
// (BlueprintCallable, BlueprintEvent)

void UWBP_ItemInteractionValueChangeButton_C::ButtonActionUnhover()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "ButtonActionUnhover");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.ExecuteUbergraph_WBP_ItemInteractionValueChangeButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInteractionValueChangeButton_C::ExecuteUbergraph_WBP_ItemInteractionValueChangeButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "ExecuteUbergraph_WBP_ItemInteractionValueChangeButton");

	Params::WBP_ItemInteractionValueChangeButton_C_ExecuteUbergraph_WBP_ItemInteractionValueChangeButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_ItemInteractionValueChangeButton_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "OnAddedToFocusPath");

	Params::WBP_ItemInteractionValueChangeButton_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.OnChangeValueButtonPressed__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWBP_ItemInteractionValueChangeButton_C::OnChangeValueButtonPressed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "OnChangeValueButtonPressed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.OnDisabled__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWBP_ItemInteractionValueChangeButton_C::OnDisabled__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "OnDisabled__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.OnReleased__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWBP_ItemInteractionValueChangeButton_C::OnReleased__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "OnReleased__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_ItemInteractionValueChangeButton_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "OnRemovedFromFocusPath");

	Params::WBP_ItemInteractionValueChangeButton_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInteractionValueChangeButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "PreConstruct");

	Params::WBP_ItemInteractionValueChangeButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemInteractionValueChangeButton.WBP_ItemInteractionValueChangeButton_C.SetButtonEnabled
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enable                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemInteractionValueChangeButton_C::SetButtonEnabled(bool Enable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ItemInteractionValueChangeButton_C", "SetButtonEnabled");

	Params::WBP_ItemInteractionValueChangeButton_C_SetButtonEnabled Parms{};

	Parms.Enable = Enable;

	UObject::ProcessEvent(Func, &Parms);
}

}

