#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MapLegend

#include "Basic.hpp"

#include "WBP_MapLegend_classes.hpp"
#include "WBP_MapLegend_parameters.hpp"


namespace SDK
{

// Function WBP_MapLegend.WBP_MapLegend_C.ExecuteUbergraph_WBP_MapLegend
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MapLegend_C::ExecuteUbergraph_WBP_MapLegend(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapLegend_C", "ExecuteUbergraph_WBP_MapLegend");

	Params::WBP_MapLegend_C_ExecuteUbergraph_WBP_MapLegend Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MapLegend.WBP_MapLegend_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MapLegend_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapLegend_C", "PreConstruct");

	Params::WBP_MapLegend_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

